### ISSUE TITLE
Code Review Comments (Swayam Chidrawar)

### ISSUE THREAD

**Issue by sway4em** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#55]
Hi, awesome job on the group project so far! I'd love to try it out once its completed. The overall structure and functionality look solid, and there are no major issues to address. I’ve outlined a few minor issues below that should be quick to fix.

1. The `Course` interface is defined but not explicitly applied when restructuring the course result from the query. For strict type enforcement, consider defining `Course` as the expected type directly in the query to ensure data conforms to this structure.
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/courses.ts#L7-L12

2. Since courseId is received from the URL, validate it before querying the database to ensure it’s a valid ID
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/courses.ts#L15

3. Validate `departmentId` to confirm it’s a valid numeric ID before querying the database. For example, making a query with a string as the `departmentId` causes an `Internal Server Error`
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/departments.ts#L31-L42

4.  Validate `planId` as an integer to prevent invalid input before querying the database. For example, making a query with a string as the `planId` causes an `Internal Server Error`
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L60-L73

5. Hardcoded placeholder data
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L99-L114

6. No confirmation message
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/plans.ts#L88

7. Validate `programId` as an integer to prevent invalid input before querying the database. For example, making a query with a string as the `programId` causes an `Internal Server Error`
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/programs.ts#L18-L27

8. Ensure prefix is a valid string format (e.g., uppercase and limited length) to prevent malformed data from reaching the database.
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/subjects.ts#L29-L38

9. Hardcoded placeholder data
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L8-L12

10. Hardcoded placeholder data
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L14-L18

11. Validate `courseId` as a numeric value to prevent invalid inputs from reaching the database
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L20-L26

12. No confirmation message
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L33

13. Confirm that course exists in the `courses` table to prevent orphaned records
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L20-L26

14. No confirmation message
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/users.ts#L25

15. No comments in the code

**Comment by KaiSnorlax** [comment]
1. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/blob/fa1aae716d9433621a885eba377c9980348a9bf2/src/api/courses.ts#L17
2. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/71
3. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/82
4. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/66
5. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/74
6. No need, the 200 response code being sent back says that it is successful
7. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/69
8. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/81
9. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/pull/80
10. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/79
11. Since courseId is a FK, it will already validate.
12. No need, the 200 response code being sent back says that it is successful
13. Since courseId is a FK, it will already validate.
14. No need, the 200 response code being sent back says that it is successful
15.
