### ISSUE TITLE
Schema/API Design comments (Eduardo Gallegos)

### ISSUE THREAD

**Issue by lalog12** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#60]
1. Add a created_at to user table to track account creation (might be good metadata to store other features such as how long it's taken user to complete degree).
2.  Add a completed_on column to completed_course for the table, which will store the day, month, and year the course was completed.
3.  Potentially add a Created_on to departments for when new departments are created.
4. /department/prefix can have a clearer name
5.  Add a boolean graduated column to user or plan that specifies if the user has graduated.
6.  Adding a course difficulty on the courses table
7.  Potentially add prerequisites and corequisites onto one table with a type column that separates prerequisites and corequisite.
8.  Program_type_id is string and can be an int for consistency.
9.  Change /program/ to /programs/ gives it a better feel
10. Add error responses to all endpoints so frontend knows how to handle errors and display appropriate messages to users
11. Add sorting options to GET requests
12. can add GPA to user table

**Comment by Nathan-Lackie** [comment]
1. Since we're using supabase auth now, account creation time is currently being tracked
2. Not planned, this is not really relevant information to our use case. Plus, it would either be inaccurate if the user was putting in a course they had completed in the past, or would require extra work for them to put in the date they completed the course.
3. Not planned for similar reasons above
4. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
5. We plan to do graduate level programs (like masters) but out of scope for this class
6. This would be interesting, not sure how we would factor this in though? We are considering adding units to course info
7. Not planned, keeping them separate simplifies our logic, and keeps our data cleanly partitioned
8. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
9. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
10. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/68
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/82
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/81
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/69
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/66
11. Not planned, sorting/filtering will be done on the UI if needed
12. Would require the user to input their GPA, as we have no integrations with their transcripts. Also isn't relevant to our use case
