### ISSUE TITLE
Schema/API Design comments (Swayam Chidrawar)

### ISSUE THREAD

**Issue by sway4em** [DegreePrerequisiteTracker/Degree-Prerequisite-Tracker#64]
1. Track Course Completion Date with a `completed_on` column
2. For collection endpoints add query parameters for sorting (e.g., sort_by, order) and filtering, this can support things like GE areas and standing requirements (e.g. junior standing).
3. Add an Audit Trail for User Plan Changes
4. Add support for different catalogs as they may change over time
5. Change /program/ to /programs/ to make the endpoints more intuitive
6. Change concentration to concentrations to make the endpoints more intuitive
7. Add error messages to all endpoints

**Comment by Nathan-Lackie** [comment]
1. Not planned, this is not really relevant information to our use case. Plus, it would either be inaccurate if the user was putting in a course they had completed in the past, or would require extra work for them to put in the date they completed the course.
2. Not planned, sorting/filtering will be done on the UI if needed
3. Interesting idea, but I ultimately don't think there's enough reason to, since course history is tracked on the user level, not the plan level, not planned
4. This is an eventual goal, but is out of scope for this class
5. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
6. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/67
7. https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/68
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/82
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/81
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/69
https://github.com/DegreePrerequisiteTracker/Degree-Prerequisite-Tracker/issues/66
